Pusher Chat iOS Example/Pusher Chat iOS Example/AppDelegate.swift
PusherChatkit/PusherChatkit.xcodeproj/project.pbxproj
Source/ChatManager.swift
Source/PCTokenProvider.swift

- `PCTestingTokenProvider` is now `PCTokenProvider`.
- `instance_id` was removed and it's not needed to be provided by the user as we will get it from the URL.
For example: `https://chatkit-test-token-provider.herokuapp.com/token?instance_id=v1:us1:1234`
----

Restructure token provider

---

Source/PusherChat.h

I've just noticed that we still have `PusherChat.h` in the [`Source/`](https://github.com/pusher/chatkit-swift/tree/master/Source).
Should be removed as part of #37 but it probably sneaked out.
----

Remove PusherChat.h

---

Cartfile
Cartfile.resolved
PusherChatkit.podspec
Source/ChatManager.swift
Source/PCTokenProvider.swift

Allow `PCTokenProvider` to take a `requestInjector`
To avoid the need to drop down into using `PPHTTPEndpointTokenProvider` from `PusherPlatform`
----

Token provider update

---

Source/PCUserSubscription.swift

🐛 Fixed bug where the user_id was not retrieved
The `user_id` key is not in the root object. Therefore `user_id` will be `nil` as it was not being retrieved properly thus causing a crash.
...
----

🐛 Fixed bug where the user_id was not retrieved

---

README.md

Add `--repo-update` flag.
Some users might have an outdated CocoaPods Specs repo, and because our pod is quite new it might fail to install Chatkit dependency. By adding flag `--repo-update` we can be sure that this will not happen.
There is just one downside, it might take longer to integrate the dependency into the project.
----

Add --repo-update flag

---

CHANGELOG.md
ChatkitiOSExample/ChatkitiOSExample/ViewController.swift
Sources/PCCurrentUser.swift
Sources/PCCursorSubscription.swift
Sources/PCRoom.swift
Sources/PCRoomDelegate.swift

because `cursor_set` is being renamed to `new_cursor` asap
this isn't compiled or tested in any way
----
CC @hamchapman

cursor_set -> new_cursor and associated renames

---

Sources/ChatManager.swift
Sources/PCCurrentUser.swift
Sources/PCCursorSubscription.swift
Sources/PCMessageSubscription.swift
Sources/PCPresenceSubscription.swift
Sources/PCRoomDelegate.swift
Sources/PCRoomSubscription.swift
Sources/PCUserSubscription.swift

This PR fixes the memory leak caused by strong references to `PCRoomDelegate`, `PCMessageSubscription` and `PCCursorSubscription` being retained.
More details can be found in #76.
----
CC @hamchapman

Fix memory leak with the PCRoomDelegate

---

Cartfile.resolved
PusherChatkit.xcodeproj/project.pbxproj
Tests/CursorTests.swift

Tests the existing behaviour. There's no hook for receiving changes to your own read cursors if you're not subscribed to the room, I'll stick a card in triage.
----
CC @hamchapman

Cursors tests

---

Tests/CursorTests.swift
Tests/Helpers/Helpers.swift

Moved the synchronous connection and room creation helpers I was using for the cursors tests in to the test helpers file so we can re-use them, and converted to use a `DispatchGroup` instead of relying on XCTest's expectations.
So we can re-use them elsewhere, and to discuss the style.
If you think this is a good idea, we should maybe write all the helpers in a synchronous style? Otherwise I'll rewrite these ones in an async style and update the tests accordingly.
----
CC @hamchapman

sync connectAsUser and createRoom tests

---

CHANGELOG.md
ChatkitiOSExample/ChatkitiOSExample/ViewController.swift
Sources/PCCurrentUser.swift
Tests/MessageTests.swift

Having a type called `PCAttachmentType` still feels a bit wrong, but I think renaming the parameter at least is an improvement.
[mimir](https://github.com/pusher/mimir/pull/440)
----
CC @hamchapman

attachmentType -> attachment

---

CHANGELOG.md
Sources/PCCurrentUser.swift
Tests/MessageTests.swift

To match the Javascript SDK...
*But* I do see the logic in having it go the other way 🤔 When you're paginating it's certainly nicer to have the newest items first. Maybe we should change it in the js sdk instead? wdyt @hamchapman?

order fetch messages by increasing id

---

Sources/PCGlobalUserStore.swift

Get users by ids now takes query parameters in a more sane way with repeating query parameters that get interpreted as an array on the server side.
because `,` could be a valid user id, which leads to all sorts of disgraces.
----
CC @hamchapman

Get users by ids v2

---

Sources/PCCurrentUser.swift
Tests/CursorTests.swift

Don't use `steppedCompletionHandler`
It introduced potential for crashes
----
CC @hamchapman

Room subscription completion handler tweaks

---

Cartfile
Cartfile.resolved
PusherChatkit.podspec
Sources/ChatManager.swift
Sources/PCCurrentUser.swift
Sources/PCReadCursorDebouncerManager.swift
Sources/PCSharedInstanceOptions.swift
Sources/PCTypingIndicatorManager.swift
Tests/CursorTests.swift

* Bump pusher-platform-swift dependency to 0.6.1
* Use `PPRepeater`s in place of `NSTimer`s
Bug fixes
----
CC @hamchapman

Timers to repeaters

---

Cartfile.resolved
Sources/PCCurrentUser.swift

Ensure that `registerForRemoteNotifications()` is called after push notifications have been enabled, even if it has already been called
To ensure that the `instanceId` is set for the push notifications SDK to be able to make the network call it needs to make.
----
CC @hamchapman

Push notification fix

---

Sources/PCCursorStore.swift

See title
In preparation for allowing custom room IDs
----
CC @hamchapman

Don't use 'userID/roomID' concatenated string for cursor store dictionary keys

---

PusherChatkit.xcodeproj/project.pbxproj
Sources/PCCurrentUser.swift
Sources/PCCursor.swift
Sources/PCDateFormatter.swift
Sources/PCMessage.swift
Sources/PCRoom.swift
Sources/PCUser.swift

Use a consistent, shared `PCDateFormatter` to format all timestamps from the server.  
Hopefully to fix #107 
----
CC @hamchapman

Use shared PCDateFormatter for all date formatting goodness

---

Cartfile.resolved
PusherChatkit.xcodeproj/project.pbxproj
Sources/ChatManager.swift
Sources/PCTokenProvider.swift
Tests/ConnectionTests.swift
Tests/Helpers/Helpers.swift

Make sure we use an encoded user ID for the test token provider's query parameter
Make user IDs with non-alphanumeric characters work.
---
**NOTE**
We need to release a new version of pusher-platform-swift and update the dev here before merging to make sure everything works.
----
CC @hamchapman

Encoded user IDs

---

Sources/PCRoomDelegate.swift

It's unnecessary
Fixes #126 
----
CC @hamchapman

Stop enforcing that PCRoomDelegates conform to NSObjectProtocol

---

CHANGELOG.md
Cartfile
PusherChatkit.podspec
Sources/ChatManager.swift
Sources/Info.plist
Sources/PCCurrentUser.swift
Sources/PCSynchronizedDictionary.swift
Tests/ChatManagerTests.swift
Tests/Supporting Files/Info.plist

- Use a serial queue with synchronous tasks for the `PCSynchronizedDictionary`.
- Remove an unused queue in `PCCurrentUser`
Reduce complexity and ensure that we have correct data. I verified by running the code below as a test
```swift
func testSyncDict() {
do {
let dict = PCSynchronizedDictionary<Int, Int>()
var iterations = 1000
DispatchQueue.concurrentPerform(iterations: iterations) { index in
dict[index] = index+1
print("SET value \(index) to \(index+1)")
let idx = dict[index]
if idx == nil {
print("NO value for \(index)")
} else {
print("GET value \(idx!) for \(index)")
}
DispatchQueue.global().sync {
iterations -= 1
guard iterations <= 0 else { return }
print("DONE")
print(dict)
}
}
}
}
```
The existing version had several cases where keys were not found because setting values using …

Sync dictionary concurrency fixes

---

Sources/PCMultipartMessageRequest.swift

`PCPartURLRequest` cannot be initialized due to internal protection level. As if no initializer provided, it's default initializer access is set to `internal`.  Need to provide a constructor implementation which is public.
Ref : [Swift Doc](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html)
Check the Section : **Default Memberwise Initializers for Structure Types**
`PCPartURLRequest` object is needed to initialized to be used by `PCPartRequest`. 
While copying the code from the [Pusher Example](https://docs.pusher.com/chatkit/reference/swift#sending-a-message), could not instantiate `PCPartURLRequest`
----

PCPartUrlRequest initializer not accessible due to internal access specifier.

---

CHANGELOG.md
PusherChatkit.podspec
Sources/ChatManager.swift
Sources/Info.plist
Sources/PCMultipartMessage.swift
Sources/PCMultipartMessageRequest.swift
Tests/ChatManagerTests.swift
Tests/Supporting Files/Info.plist

Use `public` access modifier for structs and classes that are externally facing.
Not specifying one defaults to internal and leads to unintended results.
----

Use public access modifier where needed

---

Sources/PCCurrentUser.swift

Deprecate
Because they are deprecated, and we want to encourage people to move to multipart messaging.
Eventually we will change these methods to be multipart, but we didn't want to break compatibility immedately.
----

Deprecate non-multipart messaging methods

---

Sources/PCMultipartMessage.swift

Fix refresh URL construction.
Previously it was using a relative path which meant that the result path constructed was wrong.
Fixes https://github.com/pusher/chatkit-swift/issues/167
----

Use absolute path desintation when construting request to refresh url

---

Sources/PCPayloadDeserializer.swift
Sources/PCRoom.swift
Tests/RoomTests.swift

Add unread message count and last message sent at properties to rooms.
Allows users to easily fetch unread counts for a room and to also sort rooms by last message sent.
**NOTE**: **Depends on #172 being merged first.**

Add unreadCount and lastMessageAt properties to PCRoom

---

CHANGELOG.md
PusherChatkit.podspec
Sources/ChatManager.swift
Sources/Info.plist
Sources/PCSynchronizedArray.swift
Tests/ChatManagerTests.swift
Tests/Supporting Files/Info.plist

Make PCSynchronizedArray operations serial.
All async operations were already serialised using
the barrier flag, but synchronous mutations were
being allowed to run concurrently, potentially
corrupting the underlying array.
----

Make PCSynchronizedArray operations serial

---

Tests/RoomTests.swift

Because the tests may be run in parallel, we cannot know that a RoomUpdated event is *our* room updated event without checking the id of the Room it relates to. If it is not, we should ignore it.

Fix the flakey room updated tests

---

Sources/PCMultipartMessage.swift

In order to create messages locally outside the library we need to have public initializers. Otherwise they cannot be initialized due to internal accessibilty of those initializers
The ability to setup and send messages internally without having to wait until the message is pushed through the server means we can have a "message in transit". If these initializers are internal, the entire messaging system needs to replicate the message structure. With these public initializers we create custom internal messages.
----

Public initializers for payloads in multipart message 

---

CHANGELOG.md
Sources/PCCurrentUser.swift
Sources/PCMultipartAttachmentUploader.swift
Sources/PCRoomStore.swift
Sources/PCSynchronizedArray.swift
Sources/PCSynchronizedDictionary.swift
Sources/PCUserSubscription.swift
Tests/RoomMembershipTests.swift

Remove async methods from SynchronizedArray
Over the course of multiple changes, the synchronized array has now arrived at
the only reliable implementation - a wrapper around a shared datastructure
with all access serialised via a *non-concurrent* queue.
There is no point submitting tasks to this queue asynchronously and passing in
a completion handler to be invoked when the operation is complete - all we
achieve doing this is a proliferation of callbacks and, more importantly, the
moving of the completion handler invocations in to the critical section. We
actually lose what ever concurrency there may be in the callers.

Simplify concurrency

---

CHANGELOG.md
Sources/PCCurrentUser.swift
Sources/PCUserSubscription.swift

They should be tested against the existing store and the existing entity used if there is one (after being updated with new fields).
This is because the entities hold important state (including the subscriptions, in the case of rooms), something which will be removed from them in future to save this kind of error from being possible.

Don't allow newly de-serialised entities to propagate

---

PusherChatkit.xcodeproj/project.pbxproj
Sources/DispatchSemaphore.swift
Sources/PCRoom.swift
Sources/PCUser.swift

Guard mutable properties of PCRoom and PCUser against concurrent reads/writes from different threads
Crashes and corruption await those who make concurrent access to values from different threads. We desire neither.
----

Guard mutable properties of PCUser

---

PusherChatkit.xcodeproj/xcshareddata/xcschemes/PusherChatkit.xcscheme
Sources/ChatManager.swift
Sources/PCCurrentUser.swift
Sources/PCReadCursorDebouncerManager.swift
Sources/PCTokenProvider.swift

Guard mutable properties of `PCCurrentUser`, `PCReadCursorDebouncer`, `PCTokenProvider` and `ChatManager` against concurrent reads/writes from different threads.
Improve stability of the SDK.
----

Fix for race conditions discovered with thread sanitizer

---

Chatkit/Model/Room.swift
Chatkit/Persistence/Snapshotable/Entities/RoomEntity+Snapshotable.swift
Chatkit/Test Data/RoomFactory.swift

Remove `members` and `typingMembers` properties from `Room`.
Provide room members and typing indicators from dedicated providers.
----

Remove redundant properties

---

Chatkit/View Models/MessagesViewModel.swift

When loading older messages, we were running an delete and an update on
a row with the same index within the same batch, when we added a message
at i, removed the date header at i+1 and then tried to update the
grouping of i+2, which now has index i+1 because of the removal of the
date header which was there. This crashes the app.
We now split the update batches up in to different operations for
safety, and do the bulk insert, the removal of the date header and the
fixing of the grouping in separate operations. The animations all still
overlap in time for a smooth visual transition.
The bracketing willUpdate and didUpdate callbacks are also moved in to a
function which takes a closure to execute between them so that the start
and end can be observed at the lexical block level.

Prevent attempts to both remove and update a row in a single batch

---

Demo/Controllers/MessageViewController.swift

At least when looking at the most recent history of the conversation,
the typing indicator should be made visisble when it is relevant.
----

Ensure that typing indicators are visible in demo

---

Sources/PCReadCursorDebouncerManager.swift

I was getting crashes when updating the cursor for a chat room. Code was using force unwrap after checking for nil
Here is the relevant stack trace:
```swift
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
frame #0: 0x00000001eb28b194 libswiftCore.dylib`_swift_runtime_on_report
frame #1: 0x00000001eb2e1738 libswiftCore.dylib`_swift_stdlib_reportFatalErrorInFile + 188
frame #2: 0x00000001eb02ad20 libswiftCore.dylib`function signature specialization <Arg[1] = [Closure Propagated : closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, …
```

Prevent crash due to a force unwrap when updating cursor

---

Cartfile
Cartfile.resolved
PusherChatkit.podspec
Sources/ChatManager.swift
Sources/PCCurrentUser.swift

We updated the beams sdk and updated where we use it to support multiple instances.
To test this we added a chatkit instance id into the demo app + instantiated beams e.g. our app delegate looked like the following:
```swift
let instanceLocator = "CHATKIT_INSTANCE_LOCATOR"
let pusherChat = ChatManager(
instanceLocator: instanceLocator,
tokenProvider: PCTokenProvider(url: "CHATKIT_TOKEN_PROVIDER"),
userID: "danielle",
logger: TestLogger()
)
self.pusherChat = pusherChat
// Initiate the registration process with Apple Push Notification service.
ChatManager.registerForRemoteNotifications()
self.beamsClient.start(instanceId: "BEAMS_INSTANCE_ID")
self.beamsClient.registerForRemoteNotifications()
```
This will enable people to use beams + chatkit in the same app
----

Update the beams sdk which supports multiple instances and consume

---

Chatkit.xcodeproj/project.pbxproj
Integration Tests/Supporting Files/File Lists/Carthage.xcfilelist
Unit Tests/Supporting Files/File Lists/Carthage.xcfilelist

- Add File List files to both testing targets defining Carthage dependencies.
- Add custom `CARTHAGE_PLATFORM` build setting which allows us to select correct dependencies for the selected platform.
Fix test targets for macOS failing due to missing dependencies.
----

Fix test targets for macOS

---

.gitignore
Chatkit.xcodeproj/project.pbxproj
Environment/Extensions/String+Extensions.swift
Environment/Variables/Environment.swift
Unit Tests/Tests/Environment/String+ExtensionTests.swift

Makes it possible for developers to define their instance locator in a file named `InstanceLocator` in the root of the repo.
Developers would have to do this once and then the file/value remains even if changing branches or resetting your working copy and there’s no possibility of it being accidentally checked in (unlike with the env-var in the xcschemes at present).
----

OKP `InstanceLocator` file

---

Cartfile.resolved
Unit Tests/Helpers/FakeTokenProvider.swift
Unit Tests/Tests/Authentication/Token Providers/TestTokenProviderTests.swift

The PusherPlatform `Token.token` property  was renamed to `Token.value`.  Updating code here accordingly.
So project compiles :-)
----

OKP - Update in line with PusherPlatform changes

---

Chatkit.xcodeproj/project.pbxproj
Chatkit/Networking/Model/Subscription/Wire.Event.Subscription.swift
Chatkit/Networking/Model/Wire.Cursor.swift
Chatkit/Networking/Model/Wire.Message.swift
Chatkit/Networking/Model/Wire.ReadState.swift
Unit Tests/Tests/Networking/Model/Wire.ReadState+Decodable.Tests.swift

Made `cursor` value of a `read_state` *optional*.
To fix bug when parsing code from production API
Renamed `Make InstanceLocator File` target adding spaces so that is consistent with a) the target of the same name in the PusherPlatform project and b) with the names of other targets in this project
----

OKP Cursor optional

---

Chatkit.xcworkspace/contents.xcworkspacedata
Demo.xcodeproj/project.pbxproj

Moved `PusherChatkit` from root of workspace to under Demo projects Frameworks` group. 
This resolves the issue where `Jump to Definition` takes you into the file in the package instead of the file in the Chatkit project.
----

OKP Moved `PusherChatkit` package

---

Demo.xcodeproj/project.pbxproj

1) Lowered the IPHONE IOS_DEPLOYMENT_TARGET to 10 
2) Embedded the `Environment.framework` 
1) To match the framework
2) So that it can work on real devices :-)
----

Fixed a couple of things in the Demo app project

---

Chatkit.xcodeproj/project.pbxproj
Chatkit/Chatkit/Chatkit.swift
Chatkit/Repositories/Change Reasons/JoinedRoomsRepositoryChangeReason.swift
Chatkit/Repositories/Filters/ConcreteJoinedRoomsRepositoryFilter.swift
Chatkit/Repositories/JoinedRoomsRepository.swift
Chatkit/Repositories/States/JoinedRoomsRepositoryState.swift
Chatkit/Transformer/Transformer.swift
Chatkit/View Models/Change Reasons/JoinedRoomsViewModelChangeReason.swift
Chatkit/View Models/JoinedRoomsViewModel.swift
Chatkit/View Models/States/JoinedRoomsViewModelState.swift
Test Utilities/Doubles/Repositories/JoinedRoomsRepository.swift
Test Utilities/Doubles/Repositories/JoinedRoomsRepositoryDelegate.swift
Test Utilities/Doubles/Transformer/Transformer.swift
Test Utilities/Doubles/View Models/JoinedRoomsViewModelDelegate.swift
Unit Tests/Tests/Repositories/ConcreteJoinedRoomsRepositoryTests.swift
Unit Tests/Tests/Repositories/Filters/ConcreteJoinedRoomsRepositoryFilterTests.swift
Unit Tests/Tests/Repositories/JoinedRoomsRepositoryTests.swift
Unit Tests/Tests/Repositories/States/JoinedRoomsRepositoryStateTests.swift
Unit Tests/Tests/Transformers/ConcreteTransformerTests.swift
Unit Tests/Tests/View Models/Change Reasons/JoinedRoomsViewModelChangeReasonTests.swift
Unit Tests/Tests/View Models/ConcreteJoinedRoomsViewModelTests.swift
Unit Tests/Tests/View Models/JoinedRoomsViewModelTests.swift
Unit Tests/Tests/View Models/States/JoinedRoomsViewModelStateTests.swift

This PR exposes `JoinedRoomsRepository` and `JoinedRoomsViewModel` in the public API as protocols.
Increased testability.
----

Expose JoinedRoomsRepository and JoinedRoomsViewModel as protocols

---

Chatkit/Subscriptions/Instance/ResumableSubscription.swift
Chatkit/Subscriptions/Subscription.swift
Test Utilities/Doubles/Subscriptions/Instance/InstanceWrapper.swift
Test Utilities/Doubles/Subscriptions/Instance/ResumableSubscription.swift
Unit Tests/Tests/Subscriptions/ConcreteSubscriptionTests.swift

Ensure that all closures are nill'ed off on a ResumableSubscription before calling `end()`
Fixes an infinite recursion crash when attempting to subscribe with a non-existing userId.

OKP Crash Fix

---

Chatkit/Networking/Model/Wire.Membership.swift
Chatkit/Networking/Model/Wire.Room.swift
Functional Tests/Tests/Functional.ChatkitConnected.Tests.swift
Functional Tests/Tests/Functional.JoinedRoomsProviderInitialised.Tests.swift
Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.AddedToRoom+Decodable.Tests.swift
Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.InitialState+Decodable.Tests.swift
Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.RoomUpdated+Decodable.Tests.swift
Unit Tests/Tests/Networking/Model/Subscription/Wire.Event.Subscription+Decodable.Tests.swift
Unit Tests/Tests/Networking/Model/Wire.Membership+Decodable.Tests.swift
Unit Tests/Tests/Networking/Model/Wire.Room+Decodable.Tests.swift
Unit Tests/Tests/Redux/Reducers/MasterReducerTests.swift
Unit Tests/Tests/Redux/Reducers/Model/RoomListReducerTests.swift
Unit Tests/Tests/Redux/Reducers/Model/UserReducerTests.swift
Unit Tests/Tests/Redux/Reducers/Subscriptions/User Subscription/AddedToRoomReducerTests.swift
Unit Tests/Tests/Redux/Reducers/Subscriptions/User Subscription/InitialStateReducerTests.swift
Unit Tests/Tests/Redux/Reducers/Subscriptions/User Subscription/RoomUpdatedReducerTests.swift

1. Changed `Wire.Membership.userIdentifiers` to a Set (previously an Array)
2. Dropped `Wire.Room.createdById` 
1. Makes sense for `Wire.Membership.userIdentifiers` to be a Set because the ids should be unique.
2. We don't think Wire.Room.createdById`  is required
----

Wire model updates
