pusher/chatkit-swift

- CHANGELOG.md
- Cartfile
- Cartfile.resolved
- Pusher Chat iOS Example/Pusher Chat iOS Example.xcodeproj/project.pbxproj
- Pusher Chat iOS Example/Pusher Chat iOS Example/AppDelegate.swift
- PusherChatkit.podspec
- PusherChatkit/PusherChatkit.xcodeproj/project.pbxproj
- PusherChatkit/PusherChatkit.xcodeproj/xcshareddata/xcschemes/PusherChatkit.xcscheme
- Source/Info.plist
- Source/PCCurrentUser.swift
- Source/PCRoom.swift
- Source/PCSynchronizedArray.swift
- Tests/Info.plist
> Migrate to Swift 4

- Cartfile
- Cartfile.resolved
Update Cartfile and use `pusher-platform-swift` version `0.1.31`
----
> Set to version 0.1.31

- README.md
> Update the pod version and update the framework title

- README.md
> Add PusherChatkit CocoaPods version badge

- CHANGELOG.md
- Cartfile
- Cartfile.resolved
- PusherChatkit.podspec
- Sources/ChatManager.swift
> Provide SDK info object to Instance(s) created as part of ChatManager instantiation

- Sources/ChatManager.swift
- Sources/PCCurrentUser.swift
- Sources/PCPayloadDeserializer.swift
- Sources/PCPresenceSubscription.swift
- Sources/PCUserSubscription.swift
See title
We want to use the new presence service
----
CC @hamchapman
> Use separate presence instance to communicate with chatkit_presence

- CHANGELOG.md
- Cartfile
- Cartfile.private
- Cartfile.resolved
- PusherChatkit.podspec
- PusherChatkit.xcodeproj/project.pbxproj
- Sources/PCTokenProvider.swift
- Tests/TokenProviderTests.swift
Queue token fetch requests if one is already underway
Fewer requests made to token endpoint
----
CC @hamchapman
> Queue token fetch requests if one is already underway

- Sources/PCCurrentUser.swift
Currently messages were not sending if an attachment was not set. This fixes that.
----
CC @hamchapman
> Fix sending messages when an attachment is not set

- PusherChatkit.xcodeproj/project.pbxproj
- Sources/PCCurrentUser.swift
- Sources/PCDefaults.swift
- Sources/PCReadCursorDebouncerManager.swift
- Tests/DefaultsTests.swift
Add debouncing for setting read cursors
So the service doesn't get hammered by loads of read cursor requests
----
CC @hamchapman
> Add debouncing for setting read cursors

- README.md
> added minimum versions to README

- Sources/PCBasicMessage.swift
- Sources/PCCurrentUser.swift
- Sources/PCMessage.swift
- Sources/PCPayloadDeserializer.swift
Make text required for messages
API requires it
----
CC @hamchapman
> Make text required for messages

- .gitignore
- README.md
- Tests/Config/TestConfig.swift
- Tests/Config/TestConfigExample.swift
- Tests/CurrentUserTests.swift
- Tests/Helpers/Helpers.swift
> Get the stubbed test working as a basis for writing more stubbed tests

- PusherChatkit.xcodeproj/project.pbxproj
- Tests/CursorTests.swift
- Tests/Helpers/Helpers.swift
- Tests/TypingIndicatorTests.swift
So... these work, but I'm not 100% confident in them because if you swap Alice and Bob around in the second test, then the expectations in the first hook get fulfilled twice... even though we make a whole new chat manager in the set up phase. Does something persist globally? Or is everything local to a chat manager?
----
CC @hamchapman
> Typing indicator tests

- ChatkitiOSExample/ChatkitiOSExample/Base.lproj/Main.storyboard
- ChatkitiOSExample/ChatkitiOSExample/ViewController.swift
- PusherChatkit.xcodeproj/project.pbxproj
- Sources/ChatManager.swift
- Sources/PCBasicCurrentUser.swift
- Sources/PCChatManagerDelegate.swift
- Sources/PCConnectionCoordinator.swift
- Sources/PCCurrentUser.swift
- Sources/PCPresenceSubscription.swift
- Sources/PCRoomSubscription.swift
- Sources/PCSynchronizedArray.swift
- Sources/PCUserSubscription.swift
- Tests/CurrentUserTests.swift
- Tests/CursorTests.swift
- Tests/Helpers/Helpers.swift
- Tests/Helpers/TestingDelegates.swift
- Tests/Helpers/TokenGenerator.swift
- Tests/PresenceTests.swift
- Tests/RoomMembershipTests.swift
- Tests/TypingIndicatorTests.swift
- Tests/UserSubscriptionTests.swift
Contains all of the membership tests and presence tests (which can be considered reviewed and 👍-ed).
Tests are good
----
CC @hamchapman
> Membership (and presence) tests

- CHANGELOG.md
- Sources/PCCurrentUser.swift
- Tests/CursorTests.swift
- Tests/MessageTests.swift
- Tests/PresenceTests.swift
- Tests/RoomMembershipTests.swift
- Tests/TypingIndicatorTests.swift
I have a feeling this might not be very idiomatic, in which case suggestions of alternative approaches would be great!
----
CC @hamchapman
> subscription completion handler

- Sources/PCCurrentUser.swift
- Tests/TypingIndicatorTests.swift
See title
It didn't work before 
----
CC @hamchapman
> Fix delegate being set on PCCurrentUser when calling connect multiple times

- ChatkitiOSExample/ChatkitiOSExample/Base.lproj/Main.storyboard
- ChatkitiOSExample/ChatkitiOSExample/ViewController.swift
See title
Make the example app more useful 
----
CC @hamchapman
> Add tableview to iOS example app

- Cartfile.resolved
- Sources/ChatManager.swift
- Sources/PCBasicCursor.swift
- Sources/PCBasicMessage.swift
- Sources/PCCurrentUser.swift
- Sources/PCCursorStore.swift
- Sources/PCMembershipSubscription.swift
- Sources/PCMessageSubscription.swift
- Sources/PCPayloadDeserializer.swift
- Sources/PCReadCursorDebouncerManager.swift
- Sources/PCRoom.swift
- Sources/PCRoomStore.swift
- Sources/PCTypingIndicatorManager.swift
- Sources/PCUserSubscription.swift
- Tests/CurrentUserTests.swift
- Tests/CursorTests.swift
- Tests/MessageTests.swift
- Tests/PresenceTests.swift
- Tests/RoomMembershipTests.swift
- Tests/TypingIndicatorTests.swift
Tests need running against updated API when it's ready.
----
CC @hamchapman
> treat room IDs as strings throughout

- README.md
> add note to readme

- CHANGELOG.md
- PusherChatkit.xcodeproj/project.pbxproj
- Sources/PCCurrentUser.swift
- Sources/PCMessageSubscription.swift
- Sources/PCPayloadDeserializer.swift
- Sources/PCRoom.swift
- Tests/Helpers/TestingDelegates.swift
- Tests/RoomMembershipTests.swift
- Tests/RoomTests.swift
Add support for custom data on rooms
It's good 
----
CC @hamchapman
> Room custom data

- CHANGELOG.md
- PusherChatkit.xcodeproj/project.pbxproj
- Sources/PCAttachment.swift
- Sources/PCCurrentUser.swift
- Sources/PCPayloadDeserializer.swift
- Tests/Assets/lol ? wut ?&...json
- Tests/MessageTests.swift
- Tests/PresenceTests.swift
> Add support for attachment name

- Cartfile.resolved
- Sources/PCPayloadDeserializer.swift
- Sources/PCRoom.swift
> deletedAt field on room

- Cartfile.resolved
- PusherChatkit.xcodeproj/project.pbxproj
- Sources/PCBasicCurrentUser.swift
- Sources/PCBasicMessageEnricher.swift
- Sources/PCConnectionCoordinator.swift
- Sources/PCCurrentUser.swift
- Sources/PCCursorSubscription.swift
- Sources/PCMessageSubscription.swift
- Sources/PCRoomSubscription.swift
- Tests/CurrentUserTests.swift
- Tests/Helpers/Helpers.swift
- Tests/RoomEventBufferingTests.swift
Buffer room events until initial room subscriptions have all succeeded
Make sure messages are delivered before memberships have been received, for example
----
CC @hamchapman
> Buffer room events

- Sources/PCRoom.swift
- Sources/PCSynchronizedDictionary.swift
- Tests/Helpers/Helpers.swift
- Tests/MessageTests.swift
See title
It's useful 
----
CC @hamchapman
> Add unsubscribe function to PCRoom

- Sources/PCBasicMessage.swift
- Sources/PCCurrentUser.swift
- Sources/PCMultipartMessage.swift
- Tests/MessageTests.swift
Allows fetching v3 messages.
Cause Multipart messages
----
> Add fetchMultipartMessages method

- PusherChatkit.xcodeproj/project.pbxproj
- Sources/PCCurrentUser.swift
- Sources/PCMultipartAttachmentUploader.swift
- Sources/PCMultipartMessage.swift
- Sources/PCMultipartMessageRequest.swift
- Sources/PCPayloadDeserializer.swift
- Sources/PCRoomSubscription.swift
- Sources/PCUserSubscription.swift
- Tests/Helpers/Helpers.swift
- Tests/MessageTests.swift
Allows attachment uploads using the new v3 api.
To finish off multipart messages.
----
> Upload attachments v3

- CHANGELOG.md
- PusherChatkit.podspec
- Sources/ChatManager.swift
- Sources/Info.plist
- Sources/PCMultipartMessage.swift
- Tests/ChatManagerTests.swift
- Tests/Supporting Files/Info.plist
More access modifier updates.
Because `url` is internal.
----
> Make PCMultipartAttachmenyPayload.url public

- CHANGELOG.md
- PusherChatkit.podspec
- Sources/ChatManager.swift
- Sources/Info.plist
- Sources/PCCurrentUser.swift
- Sources/PCPayloadDeserializer.swift
- Sources/PCRoom.swift
- Tests/ChatManagerTests.swift
- Tests/Supporting Files/Info.plist
Add support for push notifications room title override.
So our customers will be able to set the room title that will be visible on the push notification.
----
> Add ability to set push notification title override for a specific room

- Cartfile
- Cartfile.resolved
- Chatkit.xcodeproj/project.pbxproj
- Chatkit/Chatkit/Chatkit.swift
- Chatkit/Persistence/Model/Entities/AttachmentPartEntity+CoreDataClass.swift
- Chatkit/Persistence/Model/Entities/AttachmentPartEntity+CoreDataProperties.swift
- Chatkit/Persistence/Model/Entities/CursorEntity+CoreDataClass.swift
- Chatkit/Persistence/Model/Entities/CursorEntity+CoreDataProperties.swift
- Chatkit/Persistence/Model/Entities/InlinePartEntity+CoreDataClass.swift
- Chatkit/Persistence/Model/Entities/InlinePartEntity+CoreDataProperties.swift
- Chatkit/Persistence/Model/Entities/MessageEntity+CoreDataClass.swift
- Chatkit/Persistence/Model/Entities/MessageEntity+CoreDataProperties.swift
- Chatkit/Persistence/Model/Entities/PartEntity+CoreDataClass.swift
- Chatkit/Persistence/Model/Entities/PartEntity+CoreDataProperties.swift
- Chatkit/Persistence/Model/Entities/RoomEntity+CoreDataClass.swift
- Chatkit/Persistence/Model/Entities/RoomEntity+CoreDataProperties.swift
- Chatkit/Persistence/Model/Entities/URLPartEntity+CoreDataClass.swift
- Chatkit/Persistence/Model/Entities/URLPartEntity+CoreDataProperties.swift
- Chatkit/Persistence/Model/Entities/UserEntity+CoreDataClass.swift
- Chatkit/Persistence/Model/Entities/UserEntity+CoreDataProperties.swift
- Chatkit/Persistence/Model/Model.xcdatamodeld/Model.xcdatamodel/contents
- Chatkit/Types/Types.swift
- Unit Tests/Tests/ChatkitTests.swift
- Core Data model for storing data received from web services.
- Auto generated classes (and extensions) for entities defined in the model.
Introducing ability to persist (in-memory or on disk) data received from web services.
----
> Core Data model for storing data received from web services

- Chatkit/Chatkit/Chatkit.swift
Remove token provider
User testing
----
> Remove token provider

- Chatkit/Data Simulation/DataSimulator+Events.swift
Plan names added to data simulation.
User testing.
----
> Plan names

- Demo/Controllers/MessageViewController.swift
> Stick to bottom (in demo)

- Chatkit.xcodeproj/project.pbxproj
- Demo.xcodeproj/project.pbxproj
• Embed Chatkit framework in the demo app.
• Clean up Carthage integration to follow the official Carthage guidelines instead of using proprietary Pusher script.
Run demo app in a simulator or on a device.
----
> Embed Chatkit framework in the demo app

- Demo.xcodeproj/project.pbxproj
- Demo/Cells/MessageTableViewCell.swift
- Demo/Controllers/MessageViewController.swift
- Demo/Extensions/DateFormatter+Extensions.swift
- Demo/Supporting Files/Base.lproj/Main.storyboard
Timestamps added to Demo app
User testing
----
> Timestamps added to Demo app

- Chatkit/Data Simulation/DataSimulator+Events.swift
- Chatkit/Data Simulation/DataSimulator+MessageHistory.swift
- Chatkit/Data Simulation/DataSimulator.swift
> More test data

- Chatkit/Chatkit/Chatkit.swift
- Chatkit/Data Simulation/DataSimulator+Events.swift
- Chatkit/Data Simulation/DataSimulator+MessageHistory.swift
- Chatkit/Data Simulation/DataSimulator.swift
- Chatkit/View Models/MessagesViewModel.swift
- Chatkit/View Models/TypingUsersViewModel.swift
- Default source code formatting for Swift (Ctrl-I in Xcode).
- Speed up development
- Get rid of empty changes created by Xcode
- Readability of source code
----
> Default Xcode formatting for Swift

- .jazzy.json
- Chatkit.xcodeproj/project.pbxproj
- Chatkit/Auth/TokenProvider.swift
- Chatkit/Chatkit/Chatkit.swift
- Demo/Controllers/RoomListViewController.swift
This is a fresh PR incorporating most of the feedback from #228, because it grew very large, and I wanted to squash before merge.
Any further comments?
> Auth interface v2

- Chatkit.xcodeproj/project.pbxproj
- Chatkit.xcodeproj/xcshareddata/xcschemes/Unit Tests.xcscheme
- Chatkit/Model/Room.swift
- Unit Tests/Tests/Chatkit/ChatkitTests.swift
- Unit Tests/Tests/Model/MessageTests.swift
- Unit Tests/Tests/Model/RoomTests.swift
- Unit Tests/Tests/Store/StoreTests.swift
Get the project to compile.  However the ChatkitTests are still failing.  They will be fixed in a subsequent PR.
It doesn't at the moment. 
----
> OKP - Fix compilation

- Chatkit.xcodeproj/project.pbxproj
- Chatkit/Networking/Model/Subscription/PresenceSubscription/Wire.Event.PresenceState.swift
- Chatkit/Networking/Model/Subscription/RoomSubscription/Wire.Event.IsTyping.swift
- Chatkit/Networking/Model/Subscription/UserSubscription/Wire.Event.AddedToRoom.swift
- Chatkit/Networking/Model/Subscription/UserSubscription/Wire.Event.InitialState.swift
- Chatkit/Networking/Model/Subscription/UserSubscription/Wire.Event.ReadStateUpdated.swift
- Chatkit/Networking/Model/Subscription/UserSubscription/Wire.Event.RemovedFromRoom.swift
- Chatkit/Networking/Model/Subscription/UserSubscription/Wire.Event.RoomDeleted.swift
- Chatkit/Networking/Model/Subscription/UserSubscription/Wire.Event.RoomUpdated.swift
- Chatkit/Networking/Model/Subscription/UserSubscription/Wire.Event.UserJoinedRoom.swift
- Chatkit/Networking/Model/Subscription/UserSubscription/Wire.Event.UserLeftRoom.swift
- Chatkit/Networking/Model/Subscription/Wire.Event.EventType.swift
- Chatkit/Networking/Model/Subscription/Wire.Event.Subscription.swift
- Chatkit/Networking/Model/Subscription/Wire.Event.swift
- Chatkit/Networking/Model/Wire.Message.swift
- Chatkit/Networking/Model/Wire.MessagePart.swift
- Unit Tests/Tests/Networking/Model/Subscription/PresenceSubscription/Wire.Event.PresenceState+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/RoomSubscription/Wire.Event.IsTyping+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.AddedToRoom+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.InitialState+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.ReadStateUpdated+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.RemovedFromRoom+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.RoomDeleted+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.RoomUpdated+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.UserJoinedRoom+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/UserSubscription/Wire.Event.UserLeftRoom+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Subscription/Wire.Event.Subscription+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Wire.Message+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Wire.MessagePart+Decodable.Tests.swift
- Unit Tests/Tests/Networking/Model/Wire.User+Decodable.Tests.swift
Adds wire/network models and unit tests for JSON parsing of subscription entities.
These are fundamental to a working SDK ;-)
----
> Subscription Entity JSON parsing

- .gitignore
- Chatkit.xcodeproj/project.pbxproj
- Chatkit.xcworkspace/contents.xcworkspacedata
- Demo.xcodeproj/project.pbxproj
- Package.resolved
- Package.swift
- README.md
- System Tests/Tests/Authentication/Token Providers/TestTokenProviderTests.swift
- Unit Tests/Tests/Authentication/Token Providers/TestTokenProviderTests.swift
- Add `Package.swift` in order to define `PusherChatkit` package.
- Integrate demo app with `PusherChatkit` using Swift Package Manager.
2.0 roadmap + feature request.
----
> Support for Swift Package Manager

- Chatkit.xcodeproj/project.pbxproj
- Chatkit/Repositories/JoinedRoomsRepository.swift
- Chatkit/Repositories/MessagesRepository.swift
- Chatkit/Repositories/RoomMembersRepository.swift
- Chatkit/Repositories/TypingUsersRepository.swift
- Chatkit/View Models/JoinedRoomsViewModel.swift
- Chatkit/View Models/MessagesViewModel.swift
- Chatkit/View Models/TypingUsersViewModel.swift
- Functional Tests/Tests/Contexts.swift
- Functional Tests/Tests/Functional.ChatkitConnected.Tests.swift
- Functional Tests/Tests/Functional.ChatkitInitialised.Tests.swift
- Functional Tests/Tests/Functional.JoinedRoomsProviderInitialised.Tests.swift
- System Tests/Tests/Contexts.swift
- System Tests/Tests/System.ChatkitConnected.Tests.swift
- System Tests/Tests/System.ChatkitInitialised.Tests.swift
- System Tests/Tests/System.Uninitialised.Tests.swift
- Test Utilities/Doubles/Repositories/JoinedRoomsRepositoryDelegate.swift
- Test Utilities/Extensions/XCTest+Assertions.swift
- Test Utilities/Extensions/XCTestExpectation+ChatkitExpectations.swift
Reinstated Functional and System Tests that had been removed.
Tests are good!
----
> Reinstated Functional and System Tests that had been removed.
